proxy:
  app_port: 80
  ssl: true
  forward_headers: false
  healthcheck:
    path: /up
    interval: 3
    timeout: 5

env:
  clear:
    BLOB_STORAGE_PATH: /data/blobs
    MY_VAR: hello-from-e2e
  secret:
    - POSTGRES_PASSWORD
    - POSTGRES_HOST
    - MY_SECRET

volumes:
  - /data/blobs:/data/blobs

readiness_delay: 15
deploy_timeout: 180
drain_timeout: 30

