service: <%= ENV['REPO_NAME'] %>
image: <%= ENV['REPO_FULL'] %>

servers:
  web:
    hosts:
      - <%= ENV['INFRA_WEB_IP'] %>

proxy:
  host: <%= ENV['INFRA_WEB_IP'] %>.nip.io

ssh:
  user: root
  keys: [.kamal/ssh_key]

registry:
  server: ghcr.io
  username: <%= ENV['REPO_OWNER'] %>
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  cache:
    type: gha
    options: mode=max

accessories:
  db:
    image: supabase/postgres:17.6.1.091
    host: <%= ENV['INFRA_DB_IP'] %>
    port: "5432:5432"
    cmd: "postgres -D /etc/postgresql -c shared_buffers=1GB -c effective_cache_size=3GB -c work_mem=10MB -c maintenance_work_mem=256MB -c max_connections=100"
    env:
      secret:
        - POSTGRES_PASSWORD
    directories:
      - /data/pgdata:/var/lib/postgresql/data
